// Package todos is the todos feature's infrastructure (the impure shell): the
// ONLY code here that touches the database. The SQL is generated by sqlc from
// queries.sql into sqlcgen; Repo wraps it and maps rows to/from core.Todo.
// Reads are plain methods; writes go through WithTx so a batch of effects
// commits or rolls back together.
package todos

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"agentic-sandbox/internal/core"
	"agentic-sandbox/internal/kernel"
	"agentic-sandbox/internal/shell/todos/sqlcgen"
)

// Repo is the todos Postgres repository.
type Repo struct {
	pool *pgxpool.Pool
	q    *sqlcgen.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo {
	return &Repo{pool: pool, q: sqlcgen.New(pool)}
}

// Ping reports whether the database is reachable (used by /healthz).
func (r *Repo) Ping(ctx context.Context) error { return r.pool.Ping(ctx) }

// ListParams controls a List query. Done nil means "any".
type ListParams struct {
	Done   *bool
	Limit  int
	Offset int
}

// List returns todos newest-first. This is the READ half of the workflow; it
// lives in the shell because reading is I/O, and the API hands the result
// straight back to the client (or into pure core) as plain data.
func (r *Repo) List(ctx context.Context, p ListParams) ([]core.Todo, error) {
	rows, err := r.q.ListTodos(ctx, sqlcgen.ListTodosParams{
		Done:   p.Done,
		Limit:  int32(p.Limit),
		Offset: int32(p.Offset),
	})
	if err != nil {
		return nil, fmt.Errorf("list todos: %w", err)
	}
	todos := make([]core.Todo, len(rows))
	for i, row := range rows {
		todos[i] = toCoreTodo(row)
	}
	return todos, nil
}

// Get returns one todo or kernel.ErrNotFound.
func (r *Repo) Get(ctx context.Context, id string) (core.Todo, error) {
	row, err := r.q.GetTodo(ctx, id)
	if errors.Is(err, pgx.ErrNoRows) {
		return core.Todo{}, kernel.ErrNotFound
	}
	if err != nil {
		return core.Todo{}, fmt.Errorf("get todo: %w", err)
	}
	return toCoreTodo(row), nil
}

// --- write side: WithTx implements kernel.UnitOfWork; only kernel.Run calls it -

// WithTx runs fn inside a single database transaction, handing it a
// kernel.TodoWriter bound to that transaction. Every write fn performs commits
// together, or — on any error — they all roll back. kernel.Run is its only
// caller, and Run requires a Vetted, so every write here is both gated and
// atomic.
func (r *Repo) WithTx(ctx context.Context, fn func(kernel.TodoWriter) error) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	// Rollback is a no-op once Commit succeeds; otherwise it's the safety net.
	defer func() { _ = tx.Rollback(ctx) }()

	if err := fn(&txWriter{q: r.q.WithTx(tx)}); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit tx: %w", err)
	}
	return nil
}

// txWriter is the write surface bound to one transaction. It is unexported and
// only ever constructed inside WithTx, so writes cannot happen outside a
// transaction.
type txWriter struct {
	q *sqlcgen.Queries
}

func (w *txWriter) Upsert(ctx context.Context, t core.Todo) error {
	err := w.q.UpsertTodo(ctx, sqlcgen.UpsertTodoParams{
		ID:    t.ID,
		Title: t.Title,
		Done:  t.Done,
	})
	if err != nil {
		return fmt.Errorf("upsert todo %s: %w", t.ID, err)
	}
	return nil
}

func (w *txWriter) Delete(ctx context.Context, id string) error {
	n, err := w.q.DeleteTodo(ctx, id)
	if err != nil {
		return fmt.Errorf("delete todo %s: %w", id, err)
	}
	if n == 0 {
		return kernel.ErrNotFound
	}
	return nil
}

// toCoreTodo maps a generated row to the domain type. Kept trivial on purpose:
// the sqlc overrides (uuid->string, timestamptz->time.Time) make the fields
// line up, so there is no unwrapping of pgtype values here.
func toCoreTodo(t sqlcgen.Todo) core.Todo {
	return core.Todo{
		ID:        t.ID,
		Title:     t.Title,
		Done:      t.Done,
		CreatedAt: t.CreatedAt,
		UpdatedAt: t.UpdatedAt,
	}
}
