// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const deleteTodo = `-- name: DeleteTodo :execrows
DELETE FROM todos WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTodo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTodo = `-- name: GetTodo :one

SELECT id, title, done, created_at, updated_at
FROM todos
WHERE id = $1
`

// These are the ONLY queries against the todos table. sqlc reads this file and
// generates type-safe Go in internal/shell/sqlcgen; repo.go wraps that code and
// maps rows to/from core.Todo. To add or change a query, edit here and run
// `make sqlc`.
func (q *Queries) GetTodo(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, done, created_at, updated_at
FROM todos
WHERE ($1::boolean IS NULL OR done = $1)
ORDER BY created_at DESC, id
LIMIT $3 OFFSET $2
`

type ListTodosParams struct {
	Done   *bool
	Offset int32
	Limit  int32
}

func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos, arg.Done, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTodo = `-- name: UpsertTodo :exec
INSERT INTO todos (id, title, done)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET title = EXCLUDED.title, done = EXCLUDED.done, updated_at = now()
`

type UpsertTodoParams struct {
	ID    string
	Title string
	Done  bool
}

func (q *Queries) UpsertTodo(ctx context.Context, arg UpsertTodoParams) error {
	_, err := q.db.Exec(ctx, upsertTodo, arg.ID, arg.Title, arg.Done)
	return err
}
